openapi: 3.1.0
info:
  title: "Vluchtelingenzoeker API"
  description: "API voor het zoeken naar juridische informatie en het ophalen van begeleidingsdata voor zowel maatschappelijke als juridische trajecten."
  version: "1.0.0"
servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com
paths:
  /search:
    get:
      summary: "Zoek juridische informatie"
      operationId: search_legal_info
      parameters:
        - in: query
          name: onderwerp
          required: true
          schema:
            type: string
          description: "Het onderwerp om op te zoeken."
      responses:
        '200':
          description: "Resultaten gevonden"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titel:
                      type: string
                    link:
                      type: string
                    samenvatting:
                      type: string
        '404':
          description: "Geen zoekresultaten of bestand niet gevonden."
        '500':
          description: "Fout bij het uitvoeren van de zoekopdracht."
  /startmenu:
    get:
      summary: "Haal startmenu op"
      operationId: get_startmenu
      responses:
        '200':
          description: "Startmenu data"
          content:
            application/json:
              schema:
                type: object
  /all_procedures:
    get:
      summary: "Haal alle procedures op"
      operationId: get_all_procedures
      responses:
        '200':
          description: "Alle procedures en gerelateerde data"
          content:
            application/json:
              schema:
                type: object
  /mb_instrument:
    get:
      summary: "Haal MB‑Instrument data op"
      operationId: get_mb_instrument
      responses:
        '200':
          description: "MB‑Instrument data met alle vragen, hulplinks, voorlichting en acties"
          content:
            application/json:
              schema:
                type: object
