openapi: 3.1.0
info:
  title: "Vluchtelingenzoeker API"
  description: "API voor juridische informatie en begeleidingsdata."
  version: "1.1.0"

servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com

paths:
  /startmenu:
    get:
      summary: "Haal startmenu op"
      operationId: get_startmenu
      responses:
        '200':
          description: "Startmenu data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartMenuResponse'
        '404':
          description: "Menu niet gevonden"

components:
  schemas:
    StartMenuResponse:
      type: object
      properties:
        startVraag:
          type: string
        context:
          type: string
        basisgegevens:
          type: object
          properties:
            gemeente:
              type: string
            procedureKoppelenAanThuisland:
              type: boolean
            thuisland:
              type: string
            moedertaal:
              type: string
        menu:
          type: object
          properties:
            instructie:
              type: string
            opties:
              type: array
              items:
                type: object
                properties:
                  nummer:
                    type: integer
                  omschrijving:
                    type: string
