openapi: 3.1.0
info:
  title: "Vluchtelingenzoeker API"
  description: "API voor het zoeken naar juridische informatie en het ophalen van begeleidingsdata voor zowel maatschappelijke als juridische trajecten."
  version: "1.0.0"
servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com
paths:
  /search:
    get:
      summary: "Zoek juridische informatie"
      operationId: search_legal_info
      parameters:
        - in: query
          name: onderwerp
          required: true
          schema:
            type: string
          description: "Het onderwerp om op te zoeken."
      responses:
        '200':
          description: "Resultaten gevonden"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titel:
                      type: string
                    link:
                      type: string
                    samenvatting:
                      type: string
  /get_mb_instrument:
    get:
      summary: "Haal MB‑Instrument data op"
      operationId: get_mb_instrument
      responses:
        '200':
          description: "MB‑Instrument data met alle vragen, hulplinks, voorlichting en acties"
          content:
            application/json:
              schema:
                type: object
                properties:
                  mb_instrument:
                    type: object
                    properties:
                      title:
                        type: string
                      introductie:
                        type: string
                      instructions:
                        type: string
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            nummer:
                              type: string
                            tekst:
                              type: string
                            antwoordOpties:
                              type: array
                              items:
                                type: string
                            linksVoorlichting:
                              type: array
                              items:
                                type: string
                            voorlichtingOver:
                              type: array
                              items:
                                type: string
                            acties:
                              type: array
                              items:
                                type: string
  /all_procedures:
    get:
      summary: "Haal alle procedures op"
      operationId: get_all_procedures
      responses:
        '200':
          description: "Alle procedures, startvraag en menu-opties voor juridische en maatschappelijke trajecten"
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  startVraag:
                    type: string
                  menu:
                    type: object
                    properties:
                      instructie:
                        type: string
                      opties:
                        type: array
                        items:
                          type: object
                          properties:
                            nummer:
                              type: integer
                            omschrijving:
                              type: string
                  procedures:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        description:
                          type: string
                        steps:
                          type: array
                          items:
                            type: object
                            properties:
                              step:
                                type: integer
                              description:
                                type: string
  /ui_flow:
    get:
      summary: "Haal de gebruikersflow op"
      operationId: get_ui_flow
      responses:
        '200':
          description: "UI flow data voor navigatie door de applicatie"
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  flow:
                    type: array
                    items:
                      type: object
                      properties:
                        stepId:
                          type: string
                        description:
                          type: string
                        nextStepIfChoice1:
                          type: string
                        nextStepIfChoice2:
                          type: string
                        nextStepIfChoice3:
                          type: string
                        nextStepIfChoice4:
                          type: string
                        nextStep:
                          type: string
  /algemene_instructies:
    get:
      summary: "Haal de algemene instructies op"
      operationId: get_algemene_instructies
      responses:
        '200':
          description: "Algemene instructies voor het instrument"
          content:
            application/json:
              schema:
                type: object
                properties:
                  algemeneInstructies:
                    type: object
                    properties:
                      title:
                        type: string
                      doelEnContext:
                        type: string
                      werkwijzeEnFunctionaliteiten:
                        type: string
                      rolselectieStartvraagEnMenu:
                        type: string
                      proceshandleidingVoorHetMBInstrument:
                        type: string
                      juridischeProcedureEnInformatieophaling:
                        type: string
                      algemeneSysteemFunctionaliteit:
                        type: string
                      flexibiliteitEnSchaalbaarheid:
                        type: string
                      stijlEnFormatting:
                        type: string
                      conclusie:
                        type: string
