openapi: 3.1.0
info:
  title: "Vluchtelingenzoeker API"
  description: "API voor het zoeken naar juridische informatie en het ophalen van begeleidingsdata voor zowel maatschappelijke als juridische trajecten."
  version: "1.0.0"
servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com
paths:
  /search:
    get:
      summary: "Zoek juridische informatie"
      operationId: search_legal_info
      parameters:
        - in: query
          name: onderwerp
          required: true
          schema:
            type: string
          description: "Het onderwerp om op te zoeken."
      responses:
        '200':
          description: "Resultaten gevonden"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titel:
                      type: string
                    link:
                      type: string
                    samenvatting:
                      type: string
  /get_mb_instrument:
    get:
      summary: "Haal MB‑Instrument data op"
      operationId: get_mb_instrument
      responses:
        '200':
          description: "MB‑Instrument data met alle vragen, hulplinks, voorlichting en acties"
          content:
            application/json:
              schema:
                type: object
  /all_procedures:
    get:
      summary: "Haal alle procedures op"
      operationId: get_all_procedures
      responses:
        '200':
          description: "Alle procedures, startvraag en menu-opties voor juridische en maatschappelijke trajecten"
          content:
            application/json:
              schema:
                type: object
  /ui_flow:
    get:
      summary: "Haal de gebruikersflow op"
      operationId: get_ui_flow
      responses:
        '200':
          description: "UI flow data voor navigatie door de applicatie"
          content:
            application/json:
              schema:
                type: object
  /algemene_instructies:
    get:
      summary: "Haal de algemene instructies op"
      operationId: get_algemene_instructies
      responses:
        '200':
          description: "Algemene instructies voor het instrument"
          content:
            application/json:
              schema:
                type: object
