openapi: 3.1.0
info:
  title: "Vluchtelingenzoeker API"
  description: "API voor juridische informatie en begeleidingsdata."
  version: "1.1.0"

servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com

paths:
  /startmenu:
    get:
      summary: "Haal startmenu op"
      operationId: get_startmenu
      responses:
        '200':
          description: "Startmenu data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartMenuResponse'
        '404':
          description: "Menu niet gevonden"

  /mb_instrument:
    get:
      summary: "Haal MB‑Instrument data op"
      operationId: get_mb_instrument
      responses:
        '200':
          description: "MB‑Instrument data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MBInstrumentResponse'
        '404':
          description: "MB‑Instrument niet gevonden"

components:
  schemas:
    StartMenuResponse:
      type: object
      properties:
        startVraag:
          type: string
        context:
          type: string
        basisgegevens:
          type: object
          properties:
            gemeente:
              type: string
            procedureKoppelenAanThuisland:
              type: boolean
            thuisland:
              type: string
            moedertaal:
              type: string
        menu:
          type: object
          properties:
            instructie:
              type: string
            opties:
              type: array
              items:
                type: object
                properties:
                  nummer:
                    type: integer
                  omschrijving:
                    type: string

    MBInstrumentResponse:
      type: object
      properties:
        mb_instrument:
          type: object
          properties:
            version:
              type: string
            title:
              type: string
            introductie:
              type: string
            instructies:
              type: string
            vragen:
              type: array
              items:
                type: object
                properties:
                  nummer:
                    type: string
                  tekst:
                    type: string
                  antwoordOpties:
                    type: array
                    items:
                      type: string
                  linksVoorlichting:
                    type: array
                    items:
                      type: string
                  voorlichtingOver:
                    type: array
                    items:
                      type: string
                  acties:
                    type: array
                    items:
                      type: string
