# openapi.yaml
openapi: "3.1.0"

info:
  title: "Vluchtelingenwerk GPT API"
  version: "1.1.0"
  description: "REST‑API voor juridische informatie en maatschappelijke begeleiding."

servers:
  - url: "https://gpt-plugin-vluchtelingen.onrender.com"

paths:
  /:
    get:
      summary: "API‑status"
      operationId: "getRoot"
      responses:
        "200":
          description: "API is actief"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /all_procedures:
    get:
      summary: "Alle juridische procedures"
      operationId: "getAllProcedures"
      responses:
        "200":
          description: "Volledige set procedures"
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

  /search:
    get:
      summary: "Zoek actuele informatie"
      operationId: "searchInformation"
      parameters:
        - name: onderwerp
          in: query
          description: "Onderwerp om op te zoeken"
          required: true
          schema:
            type: string
        - name: gemeente
          in: query
          description: "Gemeente van de cliënt"
          required: true
          schema:
            type: string
        - name: thuisland
          in: query
          description: "Thuisland van de cliënt"
          required: true
          schema:
            type: string
        - name: moedertaal
          in: query
          description: "Moedertaal van de cliënt"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Zoekresultaten"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "404":
          description: "Geen resultaten gevonden"

  /generate_image:
    post:
      summary: "Genereer een afbeelding"
      operationId: "generateImage"
      parameters:
        - name: prompt
          in: query
          description: "Prompt voor beeldgeneratie"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "JSON van beeldgeneratie‑API"
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true

components:
  schemas: {}
