openapi: 3.1.0
info:
  title: "Vluchtelingenwerk GPT API"
  version: "1.1.0"
  description: "REST API voor juridische informatie en maatschappelijke begeleiding."

servers:
  - url: https://gpt-plugin-vluchtelingen.onrender.com

paths:
  /:
    get:
      summary: "API status"
      responses:
        '200':
          description: "API is actief"
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /all_procedures:
    get:
      summary: "Alle juridische procedures"
      responses:
        '200':
          description: "Configuratie van alle procedures"
          content:
            application/json:
              schema:
                type: object

  /mb_instrument:
    get:
      summary: "MB‑Instrument ophalen"
      responses:
        '200':
          description: "Configuratie van MB‑Instrument"
          content:
            application/json:
              schema:
                type: object

  /search:
    get:
      summary: "Zoek actuele informatie"
      parameters:
        - in: query
          name: onderwerp
          schema:
            type: string
          required: true
        - in: query
          name: gemeente
          schema:
            type: string
          required: true
        - in: query
          name: thuisland
          schema:
            type: string
          required: true
        - in: query
          name: moedertaal
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Geformatteerde en gefilterde zoekresultaten"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: "Geen resultaten gevonden"

  /generate_image:
    post:
      summary: "Genereer een afbeelding"
      parameters:
        - in: query
          name: prompt
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Gegenereerde afbeelding"
          content:
            application/json:
              schema:
                type: object
