openapi: 3.1.0
info:
  title: "Vluchtelingen Zoekplugin API"
  description: >
    Deze API verzorgt de DuckDuckGo-zoekfunctionaliteit voor actuele informatie met betrekking tot 
    Nederlandse asiel-, vluchtelingen-, statushouders- en migratiekwesties. Het endpoint haalt zoektermen 
    uit het bestand ZoekenInternet.json en haalt via DuckDuckGo actuele resultaten op.
  version: "1.0.0"
servers:
  - url
