name: Auto-deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync to server
      run: |
        rsync -av --delete --exclude='.git*' . root@91.99.2.139:/opt/vluchtelingen-gpt/

    - name: Restart service
      run: |
        ssh root@91.99.2.139 'systemctl restart vluchtelingen-gpt'
