name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl keep-alive ping
        run: curl -s https://gpt-plugin-vluchtelingen.onrender.com > /dev/null
