name: Auto-deploy naar Hetzner

# Trigger op elke push naar de main-branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy naar server
    runs-on: ubuntu-latest
    steps:
      # 1) Haal de code binnen
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Start de SSH-agent met je private key
      - name: Setup SSH-agent
        uses: webfactory/ssh-agent@v0.8
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) Voeg de server toe aan known_hosts om host-key verificatie te omzeilen
      - name: Voeg server toe aan known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      # 4) Sync de hele map naar je server met rsync
      - name: Rsync naar server
        run: |
          rsync -avz --delete \
            --exclude '.git*' \
            --exclude '.github' \
            ./ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}/

      # 5) (optioneel) herstart de systemd-service
      - name: Herstart service op server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \\
            "sudo systemctl daemon-reload && sudo systemctl restart bijbels-gpt.service vluchtelingen-gpt.service"
