name: Auto-deploy naar Hetzner

# Triggers bij elke push naar main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy naar Hetzner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH-agent opzetten
        uses: webfactory/ssh-agent@v0.5.4
        with:
          # Haalt je privé-sleutel op uit de GitHub Secret
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Synchroniseer bestanden via rsync
        run: |
          rsync -avz --delete \
            ./ \
            user@your.host:/opt/vluchtelingen-gpt/

      - name: Herstart systemd-service
        run: |
          ssh user@your.host "sudo systemctl restart vluchtelingen-gpt.service"
